name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: go mod download

      - name: Build production app
        run: ./scripts/buildprod.sh

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
        continue-on-error: true

      - name: Build and push Docker image
        run: |
          echo "Executing: gcloud builds submit --tag gcr.io/notely-project-1748472369/notely:latest ."
          ./simulate_gcp_build.sh
