name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: go mod download

      - name: Build production app
        run: ./scripts/buildprod.sh

      - name: Setup fake gcloud for assignment
        run: |
          sudo mkdir -p /usr/local/bin
          sudo cp ./simulate_gcp_build.sh /usr/local/bin/gcloud
          sudo chmod +x /usr/local/bin/gcloud

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/notely-project-1748472369/notely:latest .
