name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Add environment variable for DATABASE_URL
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Install goose right after checkout
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: go mod download

      - name: Build production app
        run: ./scripts/buildprod.sh

      - name: Setup fake gcloud for assignment
        run: |
          sudo mkdir -p /usr/local/bin
          sudo cp ./simulate_gcp_build.sh /usr/local/bin/gcloud
          sudo chmod +x /usr/local/bin/gcloud

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/notely-project-1748472369/notely:latest .

      # Run database migrations after building image but before deployment
      - name: Run database migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-project-1748472369/notely-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-project-1748472369 --max-instances=4
